FROM ubuntu:14.04

RUN apt-get install -y software-properties-common && \
add-apt-repository ppa:radio-astro/main && \
add-apt-repository multiverse && \
apt-get update && \
apt-get install -y casacore2=2.0.3-2trusty
